# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TimeseriesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: object=None):  # noqa: E501
        """TimeseriesResponse - a model defined in Swagger

        :param message: The message of this TimeseriesResponse.  # noqa: E501
        :type message: object
        """
        self.swagger_types = {
            'message': object
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'TimeseriesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimeseriesResponse of this TimeseriesResponse.  # noqa: E501
        :rtype: TimeseriesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> object:
        """Gets the message of this TimeseriesResponse.


        :return: The message of this TimeseriesResponse.
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message: object):
        """Sets the message of this TimeseriesResponse.


        :param message: The message of this TimeseriesResponse.
        :type message: object
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
